name = input('enter your name : ')
place = input('enter your place : ')
college = input('enter your college: ')
reg = int(input('enter your registration number: '))
print()
print('Name: ', name)
print('Place: ', place)
print('College: ', college)
print('Registration number: ', reg)
